server:
  port: 8082
spring:
  shardingsphere:
    datasource:
      names: master
      master: # 主数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds?characterEncoding=utf-8
        username: root
        password: root
    sharding:  # 分表配置
      tables:
        order:
          actual-data-nodes: master.order_${0..3}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_${id.intValue() % 4}
    props: # 显示SQL
      sql:
        show: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
logging:
  level:
    root: info
    com.sniper.springbootreadwrite.mapper: debug
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
