server:
  port: 8081
spring:
  shardingsphere:
    datasource:
      names: master,slave
      master: # 主数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds?characterEncoding=utf-8
        username: root
        password: root
      slave: # 从数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds?characterEncoding=utf-8
        username: root
        password: root
    masterslave:  # 读写分离配置
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      slave-data-source-names: slave
      name: dataSource
    props: # 显示SQL
      sql:
        show: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
logging:
  level:
    root: info
    com.sniper.springbootreadwrite.mapper: debug
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
