server:
  port: 8084
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0: # 主数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0?characterEncoding=utf-8
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1?characterEncoding=utf-8
        username: root
        password: root
    sharding:  # 分表配置
      tables:
        order:
          actual-data-nodes: ds$->{0..1}.order_$->{0..3}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline: # inline 表达式
              sharding-column: id
              algorithm-expression: order_${id.longValue() % 4}
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{id % 2}
          sharding-column: id
    props: # 显示SQL
      sql:
        show: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
logging:
  level:
    root: info
    com.sniper.shardingdbtablespringboot.mapper: debug
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
